spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: almm
    url: jdbc:mysql://212.64.2.19:3306/energy?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null